When utilizing scopes within Power Automate to create a try/catch/finally statement it can be useful to provide additional details about any errors that occured within.  The example below shows how to get the result of a Try block (scope action) after it has failed.

